# Please, edit this configuration file according to your needs
# Lines beginning with a '#' or ';' are commented 
# The section header is compulsory. For now it's only [stream]

[stream]

# This is the stream name as it appears in the logs
;name = My Radio

# The path to the playlist file
;playlist_file = /path/to/playlist.lst

# Play songs in sequence (0) or in random order (1)
random_order = 1

# Crossfading time (miliseconds)
crossfade_ms = 5000

# Your server address
;output_host = myradio.example.net

# your server 'admin' port. Note that the Shoutcast servers
# feature a 'listen'  port that is 'admin' + 1. Do not mess those
;output_port = 8000

# only meaningful for icecast servers
;output_mount = /stream
;output_user = source

#server password 
;output_password = myserversecret 

# The broadcast protocol (server type)
# valid options: 'shoutcast' and 'icecast'
;proto = shoutcast

# supported codecs 
# 'mp3', 'aac' for shoutcast
# 'mp3', 'aac', 'vorbis', 'flac' for icecast
;codec = mp3
;bitrate = 128000
;sample_rate = 44100

#server reconnect behavior
reconnect = 1
reconnect_delay_ms = 2000

# Enable the listener. Without it, the IP and port won't be considered (!) 
live_enable = 1

# IPv4 listen IP and port (0.0.0.0 means any interface)
# this is a SOURCE port, so, it must be base port (admin) +1
# in the end, both the SOURCE and the admin port will be opened in listening mode  
;live_ipv4_listen_addr = 0.0.0.0
;live_ipv4_listen_port = 8001

# IPv6 listen IP and port ('::' means any interface)
;live_ipv6_listen_addr = ::
;live_ipv6_listen_port = 8001

# Station metadata
ice_name = My Radio
;ice_description = My station description 
;ice_genre = My genre
;ice_url = https://my.radio.site.net
;ice_public = 1

user_agent = relcast/0.1


# live credentials - up to 64 different DJ for now
# Shoutcast sources does only feature a password (!).
# The password obey the 'sc_trans' rules and has a special format. 
# It consists of two fields, separated by the ':' (colon) 
# The first field is the DJ username and the second is the actual password
# So, in his broadcast app, Bob will leave the "username" field blank and
# fill only the "password" field with 'bob:secret'
# IMPORTANT: 
# The third part of the live credential is the DJ's priority!
# It is NOT part of the password!
# Bob's password is 'bob:secret' and the his DJ priority is 10
# He can kick the user 'lame' and take over the broadcast
# He can't kick Alice

;live_credential = bob:secret:10
;live_credential = alice:secret1:10
;live_credential = lame:lamecombination:1